# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/account.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

from db import database


class Ui_cinemaIXX(object):
    def setupUi(self, cinemaIXX, id):
        cinemaIXX.setObjectName("cinemaIXX")
        cinemaIXX.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(cinemaIXX)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/bg/Desktop - 1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.home = QtWidgets.QPushButton(self.centralwidget)
        self.home.setGeometry(QtCore.QRect(0, 130, 218, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.home.setFont(font)
        self.home.setStyleSheet("background-color: rgba(0, 0, 0, 64);\n"
"color: rgb(255,255,255);")
        self.home.setObjectName("home")

        self.id = id

        self.mymovies = QtWidgets.QPushButton(self.centralwidget)
        self.mymovies.setGeometry(QtCore.QRect(0, 200, 218, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.mymovies.setFont(font)
        self.mymovies.setStyleSheet("background-color: rgba(0, 0, 0, 64);\n"
"color: rgb(255,255,255);")
        self.mymovies.setObjectName("mymovies")
        self.account = QtWidgets.QPushButton(self.centralwidget)
        self.account.setGeometry(QtCore.QRect(0, 270, 218, 70))
        self.account.clicked.connect(self.showAccountInfo)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.account.setFont(font)
        self.account.setStyleSheet("background-color: rgba(0, 0, 0, 64);\n"
"color: rgb(255,255,255);")
        self.account.setObjectName("account")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(28, 670, 160, 48))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.logout.setFont(font)
        self.logout.setStyleSheet("background-color: #0984E3;\n"
"color: rgb(255,255,255);\n"
"")
        self.logout.setObjectName("logout")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(263, 150, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        self.name.setFont(font)
        self.name.setStyleSheet("color: rgb(255, 255, 255)")
        self.name.setObjectName("name")
        self.email = QtWidgets.QLabel(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(263, 220, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        self.email.setFont(font)
        self.email.setStyleSheet("color: rgb(255, 255, 255)")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(263, 290, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        self.password.setFont(font)
        self.password.setStyleSheet("color: rgb(255, 255, 255)")
        self.password.setObjectName("password")
        
        cinemaIXX.setCentralWidget(self.centralwidget)

        self.retranslateUi(cinemaIXX)
        QtCore.QMetaObject.connectSlotsByName(cinemaIXX)

        self.showAccountInfo()

    def showAccountInfo(self):
        connection = database.connect()
        acc = database.getInformasiAkun(connection, self.id)
        name = acc[0][2]
        email = acc[0][3]
        password = acc[0][4]
        self.name.setText("Name: " + str(name))
        self.email.setText("Email: " + email)
        self.password.setText("Password: " + password)

    def retranslateUi(self, cinemaIXX):
        _translate = QtCore.QCoreApplication.translate
        cinemaIXX.setWindowTitle(_translate("cinemaIXX", "Cinema IXX"))
        self.home.setText(_translate("cinemaIXX", "Home"))
        self.mymovies.setText(_translate("cinemaIXX", "My Movies"))
        self.account.setText(_translate("cinemaIXX", "Account"))
        self.logout.setText(_translate("cinemaIXX", "LOG OUT"))
        self.name.setText(_translate("cinemaIXX", "Name: "))
        self.email.setText(_translate("cinemaIXX", "Email: "))
        self.password.setText(_translate("cinemaIXX", "Password: "))


if __name__ == "__main__":
    connection = database.connect()
    database.create_tables(connection)

    app = QtWidgets.QApplication(sys.argv)
    cinemaIXX = QtWidgets.QMainWindow()
    ui = Ui_cinemaIXX()
    ui.setupUi(cinemaIXX, -1)
    cinemaIXX.show()
    sys.exit(app.exec_())
