# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db import database


class Ui_AdminPage(object):
    def setupUi(self, AdminPage):
        AdminPage.setObjectName("AdminPage")
        AdminPage.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(AdminPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/bg/AdminPage.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.addFilmButton = QtWidgets.QPushButton(self.centralwidget)
        self.addFilmButton.setGeometry(QtCore.QRect(830, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addFilmButton.setFont(font)
        self.addFilmButton.setStyleSheet("background-color: #0984E3;\n"
"color: rgb(255, 255,255);\n"
"")
        self.addFilmButton.setObjectName("addFilmButton")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(28, 670, 160, 48))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.logout.setFont(font)
        self.logout.setStyleSheet("background-color: #0984E3;\n"
"color: rgb(255,255,255);\n"
"")
        self.logout.setObjectName("logout")

        # Grid untuk menampilkan film
        self.filmGrid = QtWidgets.QWidget(self.centralwidget)
        self.filmGrid.setGeometry(QtCore.QRect(228, 90, 741, 655))
        self.filmGrid.setObjectName("filmGrid")
        self.gridLayout = QtWidgets.QGridLayout(self.filmGrid)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")

        AdminPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminPage)
        QtCore.QMetaObject.connectSlotsByName(AdminPage)
    
    def displayFilms(self):
        connection = database.connect()
        films = database.getAllFilms(connection)
        i = 0
        for i in range(len(films)):
            frame = QtWidgets.QFrame()
            frame.setMaximumSize(QtCore.QSize(140, 205))
            frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
            frame.setFrameShadow(QtWidgets.QFrame.Raised)
            frame.setObjectName("film"+str(i))

            label = QtWidgets.QLabel(frame)
            label.setScaledContents(True)
            label.setGeometry(QtCore.QRect(0, 0, 140, 205))
            label.setPixmap(QtGui.QPixmap.fromImage(QtGui.QImage.fromData(films[i][2])))

            deleteButton = QtWidgets.QPushButton(frame)
            deleteButton.setGeometry(QtCore.QRect(94, 176, 41, 23))
            deleteButton.setObjectName("deleteButton")
            deleteButton.setText("Delete")
            deleteButton.filmId = films[i][0]
            
            deleteButton.clicked.connect(lambda: self.deleteFilm())
            self.gridLayout.addWidget(frame, i // 4, i % 4, 1, 1)
            
        while i+1 < 9:
            frame = QtWidgets.QFrame()
            frame.setMaximumSize(QtCore.QSize(140, 205))
            frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
            frame.setFrameShadow(QtWidgets.QFrame.Raised)
            frame.setStyleSheet("border: transparent;")
            frame.setObjectName("placeholder")
            self.gridLayout.addWidget(frame,  (i+1) // 4, (i+1) % 4, 1, 1)
            i += 1

    def deleteFilm(self):
        sender = self.gridLayout.sender()
        connection = database.connect()
        database.deleteFilm(connection, sender.filmId)
        self.updateFilmList()

    def updateFilmList(self):
        for i in reversed(range(self.gridLayout.count())):
            widgetToRemove = self.gridLayout.itemAt(i).widget()
            widgetToRemove.setParent(None)
            widgetToRemove.deleteLater()
        self.displayFilms()

    def retranslateUi(self, AdminPage):
        _translate = QtCore.QCoreApplication.translate
        AdminPage.setWindowTitle(_translate("AdminPage", "Cinema IXX"))
        self.addFilmButton.setText(_translate("AdminPage", "Add New Film"))
        self.logout.setText(_translate("AdminPage", "LOG OUT"))


import admin_rc

if __name__ == "__main__":
    import sys
    connection = database.connect()
    database.create_tables(connection)

    app = QtWidgets.QApplication(sys.argv)
    AdminPage = QtWidgets.QMainWindow()
    ui = Ui_AdminPage()
    ui.setupUi(AdminPage)
    ui.displayFilms()
    AdminPage.show()
    sys.exit(app.exec_())
