# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_ListFilm(object):
    def setupUi(self, Form, id):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1024, 768)
        Form.setAutoFillBackground(False)
        self.Form = Form
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.id = id

        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label.setPalette(palette)
        self.label.setStyleSheet("background-image: url(:/bg/Desktop - 1.png);\n"
"color: rgb(255, 255, 255);")
        self.label.setPixmap(QtGui.QPixmap(":/bg/Desktop - 1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.homeButton = QtWidgets.QPushButton(Form)
        self.homeButton.setGeometry(QtCore.QRect(0, 130, 218, 70))
        self.homeButton.setFont(font)
        self.homeButton.setAutoFillBackground(False)
        self.homeButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 64);")
        self.homeButton.setObjectName("homeButton")
        self.myMoviesButton = QtWidgets.QPushButton(Form)
        self.myMoviesButton.setGeometry(QtCore.QRect(0, 200, 218, 70))
        self.myMoviesButton.setFont(font)
        self.myMoviesButton.setAutoFillBackground(False)
        self.myMoviesButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 64);")
        self.myMoviesButton.setObjectName("myMoviesButton")
        self.accountButton = QtWidgets.QPushButton(Form)
        self.accountButton.setGeometry(QtCore.QRect(0, 270, 218, 70))
        self.accountButton.setFont(font)
        self.accountButton.setAutoFillBackground(False)
        self.accountButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 64);")
        self.accountButton.setObjectName("accountButton")
        self.logoutButton = QtWidgets.QPushButton(Form)
        self.logoutButton.setGeometry(QtCore.QRect(28, 670, 160, 48))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("background-color: #0984E3;\n"
"color: rgb(255, 255,255);\n"
"")
        self.logoutButton.setObjectName("logoutButton")

        # Grid untuk menampilkan film
        self.filmGrid = QtWidgets.QWidget(Form)
        self.filmGrid.setGeometry(QtCore.QRect(228, 90, 741, 655))
        self.filmGrid.setObjectName("filmGrid")
        self.gridLayout = QtWidgets.QGridLayout(self.filmGrid)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cinema IXX"))
        self.homeButton.setText(_translate("Form", "Home"))
        self.myMoviesButton.setText(_translate("Form", "My Movies"))
        self.accountButton.setText(_translate("Form", "Account"))
        self.logoutButton.setText(_translate("Form", "LOG OUT"))

    def displayFilms(self):
        connection = database.connect()
        films = database.getFilmToShow(connection, self.id)
        i = 0
        for i in range(len(films)):
            frame = QtWidgets.QFrame()
            frame.setMaximumSize(QtCore.QSize(140, 205))
            frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
            frame.setFrameShadow(QtWidgets.QFrame.Raised)
            frame.setObjectName("film"+str(i))

            label = QtWidgets.QLabel(frame)
            label.setScaledContents(True)
            label.setGeometry(QtCore.QRect(0, 0, 140, 205))
            label.setPixmap(QtGui.QPixmap.fromImage(QtGui.QImage.fromData(films[i][4])))

            #filmTitle = QtWidgets.QLabel(frame)
            #filmTitle.setGeometry(QtCore.QRect(5, 270, 141, 23))
            #filmTitle.setStyleSheet("color: rgb(255, 255, 255);")
            #filmTitle.setText(films[i][1])

            buyButton = QtWidgets.QPushButton(frame)
            buyButton.setGeometry(QtCore.QRect(70, 176, 41, 23))
            buyButton.setObjectName("BuyButton")
            buyButton.setText("Buy")
            buyButton.setStyleSheet("background-color: rgb(45, 52, 54);\n color: rgb(255, 255, 255)")
            buyButton.filmId = films[i][0]
            buyButton.clicked.connect(lambda: self.popupButton(self.Form.sender().filmId, self.id))

            infoButton = QtWidgets.QPushButton(frame)
            infoButton.setGeometry(QtCore.QRect(26, 176, 41, 23))
            infoButton.setObjectName("infoButton")
            infoButton.setText("Info")
            infoButton.setStyleSheet("background-color: rgb(45, 52, 54);\n color: rgb(255, 255, 255)")
            infoButton.filmInfo = films[i]
            infoButton.clicked.connect(lambda: self.infoButton(self.Form.sender().filmInfo))

            self.gridLayout.addWidget(frame, i // 4, i % 4, 1, 1)
            
        while i+1 < 9:
            frame = QtWidgets.QFrame()
            frame.setMaximumSize(QtCore.QSize(140, 205))
            frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
            frame.setFrameShadow(QtWidgets.QFrame.Raised)
            frame.setStyleSheet("border: transparent;")
            frame.setObjectName("placeholder")
            self.gridLayout.addWidget(frame,  (i+1) // 4, (i+1) % 4, 1, 1)
            i += 1

    def buyFilm(self, id_film, frame, id_user):
        connection = database.connect()
        database.buyFilm(connection, id_film, id_user)
        self.updateFilmList()
        frame.deleteLater()

    def updateFilmList(self):
        for i in reversed(range(self.gridLayout.count())):
            widgetToRemove = self.gridLayout.itemAt(i).widget()
            widgetToRemove.setParent(None)
            widgetToRemove.deleteLater()
        self.displayFilms()
    
    def kembali(self, frame):
        frame.deleteLater()

    def popupButton(self, id_film, id_user):
        frame = QtWidgets.QFrame(self.Form)
        frame.setMaximumSize(QtCore.QSize(700, 500))
        frame.setStyleSheet("border: transparent;")
        frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame.setFrameShadow(QtWidgets.QFrame.Raised)
        frame.setObjectName("popup")

        label = QtWidgets.QLabel(frame)
        label.setScaledContents(True)
        label.setGeometry(QtCore.QRect(372, 300, 280, 150))
        label.setStyleSheet("background-color: rgb(24, 24, 24)\n; border: 1px solid rgb(45, 52, 54);")

        filmTitle = QtWidgets.QLabel(frame)
        filmTitle.setGeometry(QtCore.QRect(410, 330, 220, 25))
        filmTitle.setStyleSheet("color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(10)
        filmTitle.setFont(font)
        filmTitle.setText("Proceed your purchase?")

        beliButton = QtWidgets.QPushButton(frame)
        beliButton.setGeometry(QtCore.QRect(450, 400, 51, 23))
        beliButton.setObjectName("beliButton")
        beliButton.setText("Yes")
        beliButton.setStyleSheet("background-color: rgb(9, 132, 227);\n color: rgb(255, 255, 255);")
        beliButton.clicked.connect(lambda: self.buyFilm(id_film, frame, id_user))

        kembaliButton = QtWidgets.QPushButton(frame)
        kembaliButton.setGeometry(QtCore.QRect(520, 400, 51, 23))
        kembaliButton.setObjectName("kembaliButton")
        kembaliButton.setText("No")
        kembaliButton.setStyleSheet("background-color: rgb(255, 0, 0);\n color: rgb(255, 255, 255);")
        kembaliButton.clicked.connect(lambda: self.kembali(frame))
        
        frame.show()

    def infoButton(self, filmInfo):
        frame = QtWidgets.QFrame(self.Form)
        frame.setMaximumSize(QtCore.QSize(850, 600))
        frame.setStyleSheet("border: transparent;")
        frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame.setFrameShadow(QtWidgets.QFrame.Raised)
        frame.setObjectName("popup")

        label = QtWidgets.QLabel(frame)
        label.setScaledContents(True)
        label.setGeometry(QtCore.QRect(230, 254, 580, 280))
        label.setStyleSheet("background-color: rgb(24, 24, 24)\n; border: 1px solid rgb(45, 52, 54);")

        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(10)

        filmPoster = QtWidgets.QLabel(frame)
        filmPoster.setScaledContents(True)
        filmPoster.setGeometry(QtCore.QRect(250, 285, 140, 220))
        filmPoster.setPixmap(QtGui.QPixmap.fromImage(QtGui.QImage.fromData(filmInfo[4])))

        filmTitle = QtWidgets.QLabel(frame)
        filmTitle.setGeometry(QtCore.QRect(410, 285, 380, 25))
        filmTitle.setStyleSheet("color: rgb(255, 255, 255);")
        filmTitle.setFont(font)
        filmTitle.setText("Title\t: " + filmInfo[1])

        filmSinopsis = QtWidgets.QLabel(frame)
        filmSinopsis.setWordWrap(True)
        filmSinopsis.setGeometry(QtCore.QRect(410, 315, 380, 80))
        filmSinopsis.setStyleSheet("color: rgb(255, 255, 255);")
        filmSinopsis.setFont(font)
        filmSinopsis.setText("Synopsis\t: " + filmInfo[2])

        filmRilis = QtWidgets.QLabel(frame)
        filmRilis.setGeometry(QtCore.QRect(410, 400, 380, 25))
        filmRilis.setStyleSheet("color: rgb(255, 255, 255);")
        filmRilis.setFont(font)
        filmRilis.setText("Release\t: " + str(filmInfo[3]))

        filmHarga = QtWidgets.QLabel(frame)
        filmHarga.setGeometry(QtCore.QRect(410, 430, 380, 25))
        filmHarga.setStyleSheet("color: rgb(255, 255, 255);")
        filmHarga.setFont(font)
        filmHarga.setText("Price\t: Rp " + str(filmInfo[5]) + ",00")

        filmJumlah = QtWidgets.QLabel(frame)
        filmJumlah.setGeometry(QtCore.QRect(410, 460, 380, 25))
        filmJumlah.setStyleSheet("color: rgb(255, 255, 255);")
        filmJumlah.setFont(font)
        filmJumlah.setText("Sold\t: " + str(filmInfo[6]))

        kembaliButton = QtWidgets.QPushButton(frame)
        kembaliButton.setGeometry(QtCore.QRect(500, 500, 51, 23))
        kembaliButton.setObjectName("kembaliButton")
        kembaliButton.setStyleSheet("background-color: rgb(45, 52, 54);\n color: rgb(255, 255, 255)")
        kembaliButton.setText("Back")
        kembaliButton.clicked.connect(lambda: self.kembali(frame))
        
        frame.show()
    
		
import listfilm_rc
from db import database

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UI_ListFilm()

    connection = database.connect()
    ui.setupUi(Form, -1)
    ui.displayFilms()

    Form.show()
    sys.exit(app.exec_())
