# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\github\if2250-2021-k04-08-cinemaixx\img\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bg_rc, AdminMainWindow, CustomerMainWindow
import sys


from db import database


class Ui_MainWindow(object):
    def openCustomer(self, id):
        self.window=QtWidgets.QWidget()
        self.UI = CustomerMainWindow.CustomerMainWindow(id)
        self.UI.uiListFilm.logoutButton.clicked.connect(lambda: self.logout(self.UI.Window_ListFilm))
        self.UI.uiAccount.logout.clicked.connect(lambda: self.logout(self.UI.Window_Account))
        self.UI.uiMyMovies.logout.clicked.connect(lambda: self.logout(self.UI.Window_MyMovies))
        MainWindow.hide()

    def openAdmin(self):
        self.window=QtWidgets.QWidget()
        self.UI = AdminMainWindow.AdminMainWindow()
        self.UI.uiAdmin.logout.clicked.connect(lambda: self.logout(self.UI.UI_AdminPage))
        self.UI.uiAddFilm.logout.clicked.connect(lambda: self.logout(self.UI.UI_AddFilmPage))
        MainWindow.hide()

    def logout(self, window):
        window.hide()
        MainWindow.show()

    def login(self):
        print("login button clicked")
        email = self.lineEdit.text()
        password = self.lineEdit_2.text()

        connection = database.connect()
        result = connection.execute("SELECT * FROM akun WHERE email = ? AND password = ?",(email,password)).fetchall()
        # print(result)
        if (len(result) > 0):
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            if result[0][5] == 'ADMIN':
                print("admin found")
                #panggil windows admin
                self.openAdmin()
            else:
                print("User found!")
                #panggil window customer
                self.openCustomer(result[0][0])
        else:
            # print("User not found!")
            self.showAlert("                                   \n          User not found!          \n                                   ")

    def signUp(self):
        print("sign up button clicked")
        email = self.lineEdit.text()
        password = self.lineEdit_2.text()
        name = email.split('@')[0]

        if (email == "" or password == ""):
            self.showAlert("Harap isi data email dan password")
        else:
            connection = database.connect()
            result = connection.execute("SELECT * FROM akun WHERE email = ?",(email,)).fetchall()
            if (len(result) > 0):
                self.showAlert("                                   \n          Email Sudah Bergabung           \n                                   ")
            else:
                connection.execute("INSERT INTO akun(name, email, password) VALUES (?,?,?)", (name,email,password))
                connection.commit()
                connection.close()
                self.showInfo("Signup berhasil")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.label.setStyleSheet("background-image: url(:/newPrefix/Bioskop Digital IXX-2.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/Bioskop Digital IXX-2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(620, 320, 291, 41))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(620, 390, 291, 41))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(620, 510, 291, 41))
        self.pushButton.setStyleSheet("background-color: rgb(56, 132, 220); \n"
"font: 14pt \"Lucida Sans\";")
        self.pushButton.setObjectName("pushButton")
        #################### Button Event Login ####################
        self.pushButton.clicked.connect(self.login)
        ############################################################
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 560, 291, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(246, 204, 124);\n"
"font: 14pt \"Lucida Sans\";")
        self.pushButton_2.setObjectName("pushButton_2")
        #################### Button Event Signup ####################
        self.pushButton_2.clicked.connect(self.signUp)
        ############################################################
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def showAlert(self,err):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.setText(err)
        msg.exec_()

    def showInfo(self,info):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText(info)
        msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cinema IXX"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Sign Up"))


if __name__ == "__main__":
    connection = database.connect()
    database.create_tables(connection)
    database.create_seeder(connection)
    # connection.execute("INSERT INTO akun(phoneNumber, name, email, password) VALUES ('081234567890','dehan', 'dehan@gmail.com', 'itb1920')")
    # connection.commit()

    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
