# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db import database


class Ui_MyMovies(object):
    def setupUi(self, MyMovies, id):
        MyMovies.setObjectName("MyMovies")
        MyMovies.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MyMovies)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/bg/Desktop - 1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.id = id

        self.home = QtWidgets.QPushButton(self.centralwidget)
        self.home.setGeometry(QtCore.QRect(0, 130, 218, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.home.setFont(font)
        self.home.setStyleSheet("background-color: rgba(0, 0, 0, 64);\n"
                                "color: rgb(255,255,255);")
        self.home.setObjectName("home")
        self.mymovies = QtWidgets.QPushButton(self.centralwidget)
        self.mymovies.setGeometry(QtCore.QRect(0, 200, 218, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.mymovies.setFont(font)
        self.mymovies.setStyleSheet("background-color: rgba(0, 0, 0, 64);\n"
                                    "color: rgb(255,255,255);")
        self.mymovies.setObjectName("mymovies")
        self.account = QtWidgets.QPushButton(self.centralwidget)
        self.account.setGeometry(QtCore.QRect(0, 270, 218, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.account.setFont(font)
        self.account.setStyleSheet("background-color: rgba(0, 0, 0, 64);\n"
                                   "color: rgb(255,255,255);")
        self.account.setObjectName("account")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(28, 670, 160, 48))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.logout.setFont(font)
        self.logout.setStyleSheet("background-color: #0984E3;\n"
                                  "color: rgb(255,255,255);\n"
                                  "")
        self.logout.setObjectName("logout")

        # Grid untuk menampilkan film
        self.filmGrid = QtWidgets.QWidget(self.centralwidget)
        self.filmGrid.setGeometry(QtCore.QRect(228, 90, 741, 655))
        self.filmGrid.setObjectName("filmGrid")
        self.gridLayout = QtWidgets.QGridLayout(self.filmGrid)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.displayFilms()

        MyMovies.setCentralWidget(self.centralwidget)

        self.retranslateUi(MyMovies)
        QtCore.QMetaObject.connectSlotsByName(MyMovies)

    def displayFilms(self):
        connection = database.connect()
        films = database.getUserFilms(connection, self.id)
        i = 0
        for i in range(len(films)):
            frame = QtWidgets.QFrame()
            frame.setMaximumSize(QtCore.QSize(140, 205))
            frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
            frame.setFrameShadow(QtWidgets.QFrame.Raised)
            frame.setObjectName("film" + str(i))

            label = QtWidgets.QLabel(frame)
            label.setScaledContents(True)
            label.setGeometry(QtCore.QRect(0, 0, 140, 205))
            label.setPixmap(QtGui.QPixmap.fromImage(QtGui.QImage.fromData(films[i][4])))

            infoButton = QtWidgets.QPushButton(frame)
            infoButton.setGeometry(QtCore.QRect(48, 176, 41, 23))
            infoButton.setObjectName("infoButton")
            infoButton.setText("Info")
            infoButton.setStyleSheet("background-color: rgb(45, 52, 54);\n color: rgb(255, 255, 255)")
            infoButton.filmInfo = films[i]
            infoButton.clicked.connect(lambda: self.infoButton(self.centralwidget.sender().filmInfo))


            self.gridLayout.addWidget(frame, i // 4, i % 4, 1, 1)

        while i + 1 < 9:
            frame = QtWidgets.QFrame()
            frame.setMaximumSize(QtCore.QSize(140, 205))
            frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
            frame.setFrameShadow(QtWidgets.QFrame.Raised)
            frame.setStyleSheet("border: transparent;")
            frame.setObjectName("placeholder")
            self.gridLayout.addWidget(frame, (i + 1) // 4, (i + 1) % 4, 1, 1)
            i += 1

    def retranslateUi(self, MyMovies):
        _translate = QtCore.QCoreApplication.translate
        MyMovies.setWindowTitle(_translate("cinemaIXX", "Cinema IXX"))
        self.home.setText(_translate("cinemaIXX", "Home"))
        self.mymovies.setText(_translate("cinemaIXX", "My Movies"))
        self.account.setText(_translate("cinemaIXX", "Account"))
        self.logout.setText(_translate("cinemaIXX", "LOG OUT"))
    
    def kembali(self, frame):
        frame.deleteLater()

    def infoButton(self, filmInfo):
        frame = QtWidgets.QFrame(self.centralwidget)
        frame.setMaximumSize(QtCore.QSize(850, 600))
        frame.setStyleSheet("border: transparent;")
        frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame.setFrameShadow(QtWidgets.QFrame.Raised)
        frame.setObjectName("popup")

        label = QtWidgets.QLabel(frame)
        label.setScaledContents(True)
        label.setGeometry(QtCore.QRect(230, 254, 580, 280))
        label.setStyleSheet("background-color: rgb(24, 24, 24)\n; border: 1px solid rgb(45, 52, 54);")

        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(10)

        filmPoster = QtWidgets.QLabel(frame)
        filmPoster.setScaledContents(True)
        filmPoster.setGeometry(QtCore.QRect(250, 285, 140, 220))
        filmPoster.setPixmap(QtGui.QPixmap.fromImage(QtGui.QImage.fromData(filmInfo[4])))

        filmTitle = QtWidgets.QLabel(frame)
        filmTitle.setGeometry(QtCore.QRect(410, 285, 380, 25))
        filmTitle.setStyleSheet("color: rgb(255, 255, 255);")
        filmTitle.setFont(font)
        filmTitle.setText("Title\t: " + filmInfo[1])

        filmSinopsis = QtWidgets.QLabel(frame)
        filmSinopsis.setWordWrap(True)
        filmSinopsis.setGeometry(QtCore.QRect(410, 315, 380, 80))
        filmSinopsis.setStyleSheet("color: rgb(255, 255, 255);")
        filmSinopsis.setFont(font)
        filmSinopsis.setText("Synopsis\t: " + filmInfo[2])

        filmRilis = QtWidgets.QLabel(frame)
        filmRilis.setGeometry(QtCore.QRect(410, 400, 380, 25))
        filmRilis.setStyleSheet("color: rgb(255, 255, 255);")
        filmRilis.setFont(font)
        filmRilis.setText("Release\t: " + str(filmInfo[3]))

        filmHarga = QtWidgets.QLabel(frame)
        filmHarga.setGeometry(QtCore.QRect(410, 430, 380, 25))
        filmHarga.setStyleSheet("color: rgb(255, 255, 255);")
        filmHarga.setFont(font)
        filmHarga.setText("Price\t: Rp " + str(filmInfo[5]) + ",00")

        filmJumlah = QtWidgets.QLabel(frame)
        filmJumlah.setGeometry(QtCore.QRect(410, 460, 380, 25))
        filmJumlah.setStyleSheet("color: rgb(255, 255, 255);")
        filmJumlah.setFont(font)
        filmJumlah.setText("Sold\t: " + str(filmInfo[6]))

        kembaliButton = QtWidgets.QPushButton(frame)
        kembaliButton.setGeometry(QtCore.QRect(500, 500, 51, 23))
        kembaliButton.setObjectName("kembaliButton")
        kembaliButton.setStyleSheet("background-color: rgb(45, 52, 54);\n color: rgb(255, 255, 255)")
        kembaliButton.setText("Back")
        kembaliButton.clicked.connect(lambda: self.kembali(frame))
        
        frame.show()
    

if __name__ == "__main__":
    import sys
    connection = database.connect()
    database.create_tables(connection)

    app = QtWidgets.QApplication(sys.argv)
    MyMovies = QtWidgets.QMainWindow()
    ui = Ui_MyMovies()
    ui.setupUi(MyMovies, -1)
    MyMovies.show()
    sys.exit(app.exec_())
